/**
 * Agent fix-plan reporter — produces `SECURITY_FIX_PLAN.md`, a structured
 * remediation document optimized for coding agents (Claude Code, Cursor,
 * Codex, Copilot) to consume and patch.
 */

import type { OwaspFinding, ScanReport } from '../core/types.js';

const MAX_FIXES = 25;

export function formatFixPlan(report: ScanReport, opts: { agent?: 'claude' | 'cursor' | 'codex' | 'copilot' | 'generic' } = {}): string {
  const agent = opts.agent ?? 'generic';
  const fixes = report.findings
    .filter((f) => f.severity === 'critical' || f.severity === 'high' || f.severity === 'medium')
    .slice(0, MAX_FIXES);

  const lines: string[] = [];
  lines.push(`# Security Fix Plan`);
  lines.push('');
  lines.push(`Generated by OWASP.WTF on ${report.generatedAt}.`);
  lines.push('');
  lines.push(`## Intent`);
  lines.push('');
  lines.push(`You are a security-focused coding agent. Address each fix below in order.`);
  lines.push(`For every fix:`);
  lines.push('');
  lines.push(`1. Read the indicated file and confirm the vulnerability still exists.`);
  lines.push(`2. Apply the minimum change needed — do not refactor unrelated code.`);
  lines.push(`3. Preserve existing behavior for safe inputs.`);
  lines.push(`4. After patching, add or update a test that proves the fix.`);
  lines.push(`5. If a fix is not safe to apply automatically, leave a TODO comment and explain why.`);
  lines.push('');
  lines.push(`Do **not** introduce new dependencies unless explicitly required by the fix.`);
  lines.push('');

  if (agent === 'claude' || agent === 'generic') {
    lines.push(`## Guardrails`);
    lines.push('');
    lines.push(`- Never commit real secrets. Use environment variables and update \`.env.example\` with placeholders.`);
    lines.push(`- Never weaken cryptography to satisfy a fix (e.g. switching to MD5).`);
    lines.push(`- Never disable existing auth/authorization to make a test pass.`);
    lines.push(`- Prefer parameterized queries over string concatenation.`);
    lines.push('');
  }

  if (fixes.length === 0) {
    lines.push(`## No high-priority fixes`);
    lines.push('');
    lines.push(`No critical, high, or medium findings to address.`);
    return lines.join('\n');
  }

  lines.push(`## Fixes (${fixes.length})`);
  lines.push('');

  fixes.forEach((f, i) => {
    lines.push(`### Fix ${i + 1}: ${f.title}`);
    lines.push('');
    lines.push(`- **Severity:** ${f.severity}`);
    lines.push(`- **Confidence:** ${f.confidence}`);
    lines.push(`- **Source:** ${f.sourceTool}${f.confirmedBy && f.confirmedBy.length > 1 ? ` (confirmed by: ${f.confirmedBy.join(', ')})` : ''}`);
    lines.push(`- **OWASP:** ${(f.owaspTop10 ?? []).join(', ') || '(unmapped)'}`);
    if (f.cwe?.length) lines.push(`- **CWE:** ${f.cwe.join(', ')}`);
    if (f.cve?.length) lines.push(`- **CVE:** ${f.cve.join(', ')}`);
    if (f.file) lines.push(`- **File:** \`${f.file}${f.line ? `:${f.line}` : ''}\``);
    if (f.packageName) {
      lines.push(`- **Package:** \`${f.packageName}@${f.installedVersion ?? '?'}\`${f.fixedVersion ? ` → upgrade to \`${f.fixedVersion}\`` : ''}`);
    }
    lines.push('');
    lines.push(`**Problem:**`);
    lines.push('');
    lines.push(f.description);
    lines.push('');
    if (f.evidence) {
      lines.push(`**Evidence:**`);
      lines.push('');
      lines.push('```');
      lines.push(f.evidence.slice(0, 600));
      lines.push('```');
      lines.push('');
    }
    lines.push(`**Required fix:**`);
    lines.push('');
    lines.push(f.remediation);
    lines.push('');
    lines.push(`**Acceptance:**`);
    lines.push('');
    lines.push(acceptanceFor(f));
    lines.push('');
    if (f.references.length > 0) {
      lines.push(`**References:** ${f.references.slice(0, 3).join(' · ')}`);
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  });

  return lines.join('\n');
}

function acceptanceFor(f: OwaspFinding): string {
  if (f.packageName && f.fixedVersion) {
    return `Re-run \`owasp-wtf scan\` and confirm ${f.id} no longer appears for \`${f.packageName}\`. Lockfile updated. Tests pass.`;
  }
  if (f.category === 'secrets') {
    return `No literal secret remains in source. The credential has been rotated and is loaded from an environment variable. \`owasp-wtf quick\` reports no secrets.`;
  }
  if (f.category === 'iac' || f.category === 'container') {
    return `\`owasp-wtf scan\` no longer reports ${f.id} for \`${f.file}\`. The misconfiguration is fixed without breaking the build.`;
  }
  return `Re-running \`owasp-wtf scan\` no longer reports ${f.id} for \`${f.file ?? 'this code path'}\`. A regression test covers the previously-vulnerable input.`;
}
