/**
 * Generated by xCoder. Do not edit by hand.
 *
 * STANDALONE OpenCode plugin — zero external dependencies.
 * All flow-engine logic is inlined so the plugin loads in any environment
 * (OpenCode GUI app, launcher mode, or npm auto-install) without requiring
 * @xcoder/flow-engine to be resolvable.
 *
 * Spec source: docs/architecture/xcoder-flow-engine-v1.md
 *              docs/specs/xcoder-opencode-gui-integration.md
 */

import type { Plugin } from "@opencode-ai/plugin"
import { execSync } from "node:child_process"
import { readFileSync, existsSync, writeFileSync, mkdirSync } from "node:fs"
import { join } from "node:path"

/* ═══════════════════════════════════════════════════════════════════════ */
/*  Types                                                                  */
/* ═══════════════════════════════════════════════════════════════════════ */

type ToolInput = Record<string, unknown>

type GuardContext = {
  state: string
  branch: string
  repo: string
  daemon: { lastVerdict: (check: string) => Promise<DaemonVerdict | undefined> }
}

type DaemonVerdict = { check: string; ok: boolean; at: string; summary?: string }

type GuardResult =
  | { ok: true; mutate?: ToolInput }
  | { ok: false; reason: string }

type Guidelines = {
  source: string
  branched: { prefix: string[]; off: string }
  specify: { specRequired: boolean; specPath?: string }
  qa: { typecheck?: string; test?: string; lint?: string; coverageMin?: number }
  maintain: { refactorLocThreshold?: number; depFreshnessDays?: number }
  policies?: Record<string, 'block' | 'warn' | 'off'>
}

type Policy = {
  id: string
  on: { tool: RegExp | string } & Record<string, unknown>
  severity?: 'block' | 'warn'
  only?: string | string[]
  guard: (args: { ctx: GuardContext; input: ToolInput; guidelines: Guidelines }) => GuardResult | Promise<GuardResult>
}

type Transition = {
  id?: string
  from: string | string[]
  to: string
  on: { tool: RegExp | string } & Record<string, unknown>
  guard?: (args: { ctx: GuardContext; input: ToolInput; guidelines: Guidelines }) => GuardResult | Promise<GuardResult>
  verify?: (args: { ctx: GuardContext; input: ToolInput; result: ToolInput; guidelines: Guidelines }) => GuardResult | Promise<GuardResult>
}

type Flow = {
  id: string
  states: string[]
  initial: string
  transitions: Transition[]
  policies: Policy[]
}

/* ═══════════════════════════════════════════════════════════════════════ */
/*  Flow definition — sdlc.simple.v1 (inlined)                             */
/* ═══════════════════════════════════════════════════════════════════════ */

const flow: Flow = {
  id: 'sdlc.simple.v1',
  states: ['idle', 'specify', 'prioritize', 'scoped', 'branched', 'qa', 'maintain'],
  initial: 'idle',

  transitions: [
    {
      id: 'scoped→branched',
      from: ['idle', 'scoped'],
      to: 'branched',
      on: { tool: /^Bash$/, command: /^gits+checkouts+-bs+/ },
      guard: ({ ctx, input, guidelines }) => {
        const cmd = (input as { command?: string }).command ?? ''
        const slug = cmd.split(/s+/).at(3) ?? ''
        const allowed = guidelines.branched.prefix.some((p) => slug.startsWith(p))
        if (!allowed) {
          return {
            ok: false,
            reason: `branch slug must start with one of: ${guidelines.branched.prefix.join(' | ')}`,
          }
        }
        if (ctx.branch !== guidelines.branched.off) {
          return {
            ok: false,
            reason: `must branch off ${guidelines.branched.off} (currently on ${ctx.branch})`,
          }
        }
        return { ok: true }
      },
      verify: async ({ ctx, guidelines }) => ({
        ok: ctx.branch !== guidelines.branched.off,
        reason: `expected HEAD to be on a non-integration branch after checkout (still on ${ctx.branch})`,
      }),
    },
    {
      id: 'branched→qa',
      from: 'branched',
      to: 'qa',
      on: { tool: /^Bash$/, command: /^gits+commits+/ },
      guard: () => ({ ok: true }),
    },
  ],

  policies: [
    {
      id: 'no-edit-on-integration',
      on: { tool: /^(Edit|Write|MultiEdit|NotebookEdit)$/ },
      guard: ({ ctx, guidelines }) => {
        if (process.env['XCODER_ALLOW_INTEGRATION_EDIT'] === '1') return { ok: true }
        return ctx.branch === guidelines.branched.off
          ? {
              ok: false,
              reason: `refusing edits on ${guidelines.branched.off}; create a feature branch first (or set XCODER_ALLOW_INTEGRATION_EDIT=1)`,
            }
          : { ok: true }
      },
    },
    {
      id: 'branch-prefix-must-match',
      on: { tool: /^Bash$/, command: /^gits+(checkouts+-b|switchs+-c)s+/ },
      guard: ({ input, guidelines }) => {
        const cmd = (input as { command?: string }).command ?? ''
        const slug = cmd.split(/s+/).at(3) ?? ''
        const allowed = guidelines.branched.prefix.some((p) => slug.startsWith(p))
        return allowed
          ? { ok: true }
          : {
              ok: false,
              reason: `branch slug must start with one of: ${guidelines.branched.prefix.join(' | ')}`,
            }
      },
    },
    {
      id: 'commit-must-reference-issue',
      on: { tool: /^Bash$/, command: /^gits+commit/ },
      guard: ({ input, guidelines }) => {
        if (process.env['XCODER_SKIP_ISSUE_REF'] === '1') return { ok: true }
        if (!guidelines.specify.specRequired) return { ok: true }
        const cmd = (input as { command?: string }).command ?? ''
        if (/--no-verify|--amend|--allow-empty/.test(cmd)) return { ok: true }
        if (!/(s-m|--message=)/.test(cmd)) return { ok: true }
        const accepted = /(#d+|(closes|fixes|resolves)s+#d+|issues?[s/]d+)/i
        return accepted.test(cmd)
          ? { ok: true }
          : {
              ok: false,
              reason:
                'commit message must reference an issue (#N, fixes #N, closes #N, resolves #N, issue 42, issues/42)',
            }
      },
    },
    {
      id: 'typecheck-must-pass-before-commit',
      on: { tool: /^Bash$/, command: /^gits+commit/ },
      guard: async ({ ctx, input, guidelines }) => {
        if (process.env['XCODER_SKIP_QA_GATE'] === '1') return { ok: true }
        if (!guidelines.qa.typecheck) return { ok: true }
        const cmd = (input as { command?: string }).command ?? ''
        if (/--no-verify|--amend/.test(cmd)) return { ok: true }
        const verdict = await ctx.daemon.lastVerdict('typecheck')
        if (!verdict) {
          return {
            ok: false,
            reason: `typecheck verdict missing or stale — run \`xc qa typecheck\` (or \`${guidelines.qa.typecheck}\`) first, or XCODER_SKIP_QA_GATE=1`,
          }
        }
        if (!verdict.ok) {
          return {
            ok: false,
            reason: `typecheck failing${verdict.summary ? ` (${verdict.summary})` : ''} — run \`xc qa typecheck\` and fix before committing`,
          }
        }
        return { ok: true }
      },
    },
  ],
}

/* ═══════════════════════════════════════════════════════════════════════ */
/*  Guidelines resolution                                                  */
/* ═══════════════════════════════════════════════════════════════════════ */

function resolveGuidelines(): Guidelines {
  const cwd = process.cwd()
  let config: Partial<Guidelines> | undefined
  let inferred: Partial<Guidelines> | undefined

  try {
    const cachePath = join(cwd, '.xcoder', 'guidelines.cache.json')
    if (existsSync(cachePath)) {
      inferred = JSON.parse(readFileSync(cachePath, 'utf-8')) as Partial<Guidelines>
    }
  } catch { /* ignore */ }

  try {
    const configPath = join(cwd, '.xcoder', 'guidelines.yaml')
    if (existsSync(configPath)) {
      // YAML parser not inlined — fall back to cache/defaults for now
    }
  } catch { /* ignore */ }

  const merged: Guidelines = {
    source: 'default',
    branched: { prefix: ['feat/', 'fix/', 'docs/', 'test/', 'chore/'], off: 'main' },
    specify: { specRequired: false },
    qa: {},
    maintain: {},
    ...inferred,
    ...config,
  }

  return merged
}

/* ═══════════════════════════════════════════════════════════════════════ */
/*  Verdict / cache helpers                                                */
/* ═══════════════════════════════════════════════════════════════════════ */

function loadVerdict(repo: string, check: string): Promise<DaemonVerdict | undefined> {
  try {
    const path = join(repo, '.xcoder', 'verdicts', `${check}.json`)
    if (!existsSync(path)) return Promise.resolve(undefined)
    const raw = readFileSync(path, 'utf-8')
    const v = JSON.parse(raw) as { ok: boolean; at: string; summary?: string }
    // Treat verdicts older than 5 minutes as stale
    const ageMs = Date.now() - new Date(v.at).getTime()
    if (ageMs > 5 * 60 * 1000) return Promise.resolve(undefined)
    return Promise.resolve({ check, ok: v.ok, at: v.at, summary: v.summary })
  } catch {
    return Promise.resolve(undefined)
  }
}

/* ═══════════════════════════════════════════════════════════════════════ */
/*  Flow-state tracking (for Desktop GUI visibility)                       */
/* ═══════════════════════════════════════════════════════════════════════ */

type FlowState = {
  phase: string
  enteredAt: string
  history: Array<{ from: string; to: string; at: string; reason?: string }>
  pendingChecks: string[]
}

const STATE_PATH = '.xcoder/opencode-desktop-state.json'

function loadState(cwd: string): FlowState {
  try {
    const p = join(cwd, STATE_PATH)
    if (!existsSync(p)) return { phase: flow.initial, enteredAt: new Date().toISOString(), history: [], pendingChecks: [] }
    const raw = readFileSync(p, 'utf-8')
    const parsed = JSON.parse(raw) as FlowState
    if (parsed.phase && Array.isArray(parsed.history)) return parsed
  } catch { /* ignore */ }
  return { phase: flow.initial, enteredAt: new Date().toISOString(), history: [], pendingChecks: [] }
}

function saveState(cwd: string, state: FlowState): void {
  try {
    const dir = join(cwd, '.xcoder')
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    writeFileSync(join(cwd, STATE_PATH), JSON.stringify(state, null, 2) + '
', 'utf-8')
  } catch { /* best-effort */ }
}

function transitionState(current: FlowState, to: string, reason?: string): FlowState {
  const entry: FlowState['history'][number] = { from: current.phase, to, at: new Date().toISOString(), reason }
  return {
    phase: to,
    enteredAt: new Date().toISOString(),
    history: [...current.history.slice(-49), entry], // keep last 50
    pendingChecks: [], // reset on transition; will be repopulated by guards
  }
}

/* ═══════════════════════════════════════════════════════════════════════ */
/*  Dispatch logic (inlined from flow-engine)                              */
/* ═══════════════════════════════════════════════════════════════════════ */

interface PreToolInput {
  hook_event_name: 'PreToolUse'
  tool_name: string
  tool_input: ToolInput
}

interface PostToolInput {
  hook_event_name: 'PostToolUse'
  tool_name: string
  tool_input: ToolInput
  tool_response: ToolInput
}

interface DispatchDecision {
  outcome: 'allow' | 'block' | 'warn' | 'mutate'
  reason?: string
  mutated?: ToolInput
  matchedId?: string
}

const ALLOW: DispatchDecision = { outcome: 'allow' }

function dispatch({ flow, guidelines, ctx, hook }: { flow: Flow; guidelines: Guidelines; ctx: GuardContext; hook: PreToolInput | PostToolInput }): DispatchDecision | Promise<DispatchDecision> {
  if (hook.hook_event_name === 'PreToolUse') {
    for (const p of flow.policies) {
      const effective = effectiveSeverity(p, guidelines)
      if (effective === 'off') continue
      if (!matches(p.on, hook.tool_name, hook.tool_input)) continue
      if (!appliesInState(p.only, ctx.state)) continue
      const result = p.guard({ ctx, input: hook.tool_input, guidelines })
      const guardResult = result instanceof Promise ? undefined : result
      if (guardResult) {
        if (!guardResult.ok) {
          return { outcome: effective === 'warn' ? 'warn' : 'block', reason: guardResult.reason, matchedId: p.id }
        }
        if (guardResult.mutate) return { outcome: 'mutate', mutated: guardResult.mutate, matchedId: p.id }
      } else {
        return (async () => {
          const r = await result
          if (!r.ok) return { outcome: effective === 'warn' ? 'warn' : 'block', reason: r.reason, matchedId: p.id }
          if (r.mutate) return { outcome: 'mutate', mutated: r.mutate, matchedId: p.id }
          return ALLOW
        })()
      }
    }
    for (const t of flow.transitions) {
      if (!matches(t.on, hook.tool_name, hook.tool_input)) continue
      if (!appliesInState(t.from, ctx.state)) continue
      if (!t.guard) continue
      const result = t.guard({ ctx, input: hook.tool_input, guidelines })
      const guardResult = result instanceof Promise ? undefined : result
      const id = t.id ?? `${asArray(t.from)[0]}→${t.to}`
      if (guardResult) {
        if (!guardResult.ok) return { outcome: 'block', reason: guardResult.reason, matchedId: id }
        if (guardResult.mutate) return { outcome: 'mutate', mutated: guardResult.mutate, matchedId: id }
        return { outcome: 'allow', matchedId: id }
      } else {
        return (async () => {
          const r = await result
          if (!r.ok) return { outcome: 'block', reason: r.reason, matchedId: id }
          if (r.mutate) return { outcome: 'mutate', mutated: r.mutate, matchedId: id }
          return { outcome: 'allow', matchedId: id }
        })()
      }
    }
    return ALLOW
  }

  for (const t of flow.transitions) {
    if (!matches(t.on, hook.tool_name, hook.tool_input)) continue
    if (!appliesInState(t.from, ctx.state) && !appliesInState(t.to, ctx.state)) continue
    if (!t.verify) continue
    const result = t.verify({ ctx, input: hook.tool_input, result: hook.tool_response, guidelines })
    const id = t.id ?? `${asArray(t.from)[0]}→${t.to}`
    const guardResult = result instanceof Promise ? undefined : result
    if (guardResult) {
      if (!guardResult.ok) return { outcome: 'block', reason: guardResult.reason, matchedId: id }
    } else {
      return (async () => {
        const r = await result
        if (!r.ok) return { outcome: 'block', reason: r.reason, matchedId: id }
        return ALLOW
      })()
    }
  }
  return ALLOW
}

function matches(matcher: { tool: RegExp | string } & Record<string, unknown>, toolName: string, toolInput: ToolInput): boolean {
  if (typeof matcher.tool === 'string') {
    if (matcher.tool !== toolName) return false
  } else if (!matcher.tool.test(toolName)) return false
  for (const key of Object.keys(matcher)) {
    if (key === 'tool') continue
    const expected = matcher[key]
    const actual = toolInput[key]
    if (!fieldMatches(expected, actual)) return false
  }
  return true
}

function fieldMatches(expected: unknown, actual: unknown): boolean {
  if (expected === undefined) return true
  if (expected instanceof RegExp) return typeof actual === 'string' && expected.test(actual)
  return expected === actual
}

function appliesInState(scope: string | string[] | undefined, current: string): boolean {
  if (scope === undefined) return true
  return asArray(scope).includes(current)
}

function asArray<T>(v: T | T[]): T[] {
  return Array.isArray(v) ? v : [v]
}

function effectiveSeverity(p: Policy, guidelines: Guidelines): 'block' | 'warn' | 'off' {
  const override = guidelines.policies?.[p.id]
  if (override === 'block' || override === 'warn' || override === 'off') return override
  return p.severity === 'warn' ? 'warn' : 'block'
}

/* ═══════════════════════════════════════════════════════════════════════ */
/*  Plugin runtime                                                         */
/* ═══════════════════════════════════════════════════════════════════════ */

const PRE_TIMEOUT_MS = 5000
const POST_TIMEOUT_MS = 10000
const BOOT_RITUAL = true

function buildContext(state: string): GuardContext {
  const repo = process.cwd()
  return {
    state,
    branch: detectBranch(),
    repo,
    daemon: { lastVerdict: async (check: string) => loadVerdict(repo, check) },
  }
}

function detectBranch(): string {
  try {
    return execSync("git rev-parse --abbrev-ref HEAD", { cwd: process.cwd(), encoding: "utf8" }).trim()
  } catch {
    return "unknown"
  }
}

function withTimeout<T>(p: Promise<T>, ms: number, label: string): Promise<T> {
  return Promise.race([
    p,
    new Promise<T>((_, reject) =>
      setTimeout(() => reject(new Error(`xcoder ${label} timed out after ${ms}ms`)), ms),
    ),
  ])
}

function runBootRitual(): string {
  try {
    const raw = execSync("xc boot --json", { cwd: process.cwd(), encoding: "utf8", timeout: 5000 })
    const parsed = JSON.parse(raw)
    const sections: string[] = [
      "> You are operating as **xCoder** (autonomous SWE agent framework). Host: OpenCode.",
      "",
    ]
    if (parsed.projectName) sections.push(`project: ${parsed.projectName}`)
    if (parsed.branch) sections.push(`branch:  ${parsed.branch} (${parsed.changedFiles > 0 ? parsed.changedFiles + ' changed' : 'clean'})`)
    if (parsed.orientation) sections.push("", "## ORIENTATION", "", parsed.orientation)
    return sections.join("\n")
  } catch {
    return "> You are operating as **xCoder**. Host: OpenCode. (boot ritual unavailable)"
  }
}

async function injectSystemMessage(client: Record<string, unknown>, body: string): Promise<void> {
  try {
    const c = client as Record<string, unknown>
    if (typeof (c.session as Record<string, unknown> | undefined)?.appendSystemMessage === "function") {
      await ((c.session as Record<string, (msg: string) => Promise<void>>).appendSystemMessage)(body)
    } else if (typeof c.systemMessage === "function") {
      await (c as { systemMessage: (msg: string) => Promise<void> }).systemMessage(body)
    }
  } catch {
    // best-effort
  }
}

const Xcoder: Plugin = async ({ client }) => {
  const guidelines = resolveGuidelines()
  let flowState = loadState(process.cwd())

  return {
    "session.created": async () => {
      if (!BOOT_RITUAL) return
      const body = runBootRitual()
      await injectSystemMessage(client, body)
    },

    "session.compacted": async () => {
      if (!BOOT_RITUAL) return
      const body = runBootRitual()
      await injectSystemMessage(client, body)
    },

    "tool.execute.before": async (input, output) => {
      const ctx = buildContext(flowState.phase)
      const decision = await withTimeout(
        Promise.resolve(dispatch({
          flow,
          guidelines,
          ctx,
          hook: {
            hook_event_name: "PreToolUse",
            tool_name: String(input.tool),
            tool_input: (output.args as Record<string, unknown>) ?? {},
          },
        })),
        PRE_TIMEOUT_MS,
        "pre-tool",
      )
      if (decision.outcome === "block") {
        throw new Error(`[xcoder] ${decision.matchedId ?? "guard"} blocked: ${decision.reason ?? "no reason"}`)
      }
      if (decision.outcome === "mutate" && decision.mutated) {
        Object.assign(output.args as Record<string, unknown>, decision.mutated)
      }
      // On successful transition, advance flow state and persist
      if (decision.outcome === "allow" && decision.matchedId) {
        const matchedTransition = flow.transitions.find(t =>
          (t.id ?? `${asArray(t.from)[0]}→${t.to}`) === decision.matchedId
        )
        if (matchedTransition && appliesInState(matchedTransition.from, flowState.phase)) {
          flowState = transitionState(flowState, matchedTransition.to, `tool: ${String(input.tool)}`)
          saveState(process.cwd(), flowState)
        }
      }
    },

    "tool.execute.after": async (input, output) => {
      const ctx = buildContext(flowState.phase)
      const decision = await withTimeout(
        Promise.resolve(dispatch({
          flow,
          guidelines,
          ctx,
          hook: {
            hook_event_name: "PostToolUse",
            tool_name: String(input.tool),
            tool_input: (output.args as Record<string, unknown>) ?? {},
            tool_response: ({} as Record<string, unknown>),
          },
        })),
        POST_TIMEOUT_MS,
        "post-tool",
      )
      if (decision.outcome === "block") {
        throw new Error(`[xcoder] ${decision.matchedId ?? "verify"} failed: ${decision.reason ?? "no reason"}`)
      }
    },
  }
}

export default Xcoder
export { Xcoder }
